<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Presentation\wwwroot\Admin\assets\css\Comment.css" />
    <Content Include="Presentation\wwwroot\Admin\assets\css\nucleo-icons.css" />
    <Content Include="Presentation\wwwroot\Admin\assets\css\nucleo-svg.css" />
    <Content Include="Presentation\wwwroot\Admin\assets\css\soft-ui-dashboard.css" />
    <Content Include="Presentation\wwwroot\Admin\assets\css\soft-ui-dashboard.css.map" />
    <Content Include="Presentation\wwwroot\Admin\assets\css\soft-ui-dashboard.min.css" />
    <Content Include="Presentation\wwwroot\Admin\assets\fonts\nucleo-icons.eot" />
    <Content Include="Presentation\wwwroot\Admin\assets\fonts\nucleo-icons.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\fonts\nucleo-icons.ttf" />
    <Content Include="Presentation\wwwroot\Admin\assets\fonts\nucleo-icons.woff" />
    <Content Include="Presentation\wwwroot\Admin\assets\fonts\nucleo-icons.woff2" />
    <Content Include="Presentation\wwwroot\Admin\assets\fonts\nucleo.eot" />
    <Content Include="Presentation\wwwroot\Admin\assets\fonts\nucleo.ttf" />
    <Content Include="Presentation\wwwroot\Admin\assets\fonts\nucleo.woff" />
    <Content Include="Presentation\wwwroot\Admin\assets\fonts\nucleo.woff2" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\apple-icon.png" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\bg1.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\bruce-mars.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved-10.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved-11.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved-6.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved-8.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved0.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved1.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved10.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved11-small.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved11.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved12.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved13.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved14.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved19.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved2.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved21.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved3.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved4.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved5-small.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved5.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved6-small.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved6.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved7.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved8.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\curved9.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\curved-images\white-curved.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\down-arrow-dark.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\down-arrow-white.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\down-arrow.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\favicon.png" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\home-decor-1.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\home-decor-2.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\home-decor-3.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\illustrations\rocket-dark.png" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\illustrations\rocket-white.png" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\ivana-square.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\ivancik.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\kal-visuals-square.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\logo-ct-dark.png" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\logo-ct.png" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\logos\mastercard.png" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\logos\visa.png" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\marie.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\shapes\pattern-lines.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\shapes\shape-1.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\shapes\shape-2.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\shapes\shape-3.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\shapes\wave-down.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\shapes\wave-up.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\shapes\waves-gray.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\shapes\waves-white.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\small-logos\icon-sun-cloud.png" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\small-logos\logo-atlassian.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\small-logos\logo-invision.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\small-logos\logo-jira.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\small-logos\logo-slack.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\small-logos\logo-spotify.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\small-logos\logo-webdev.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\small-logos\logo-xd.svg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\team-1.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\team-2.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\team-3.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\team-4.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\theme\angular.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\theme\bootstrap.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\theme\dribbble.png" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\theme\dropbox.png" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\theme\mastercard.png" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\theme\paypal.png" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\theme\react.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\theme\sketch.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\theme\slack.png" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\theme\spotify.jpeg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\theme\tim.png" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\theme\unass.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\theme\visa.png" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\theme\vue.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\img\vr-bg.jpg" />
    <Content Include="Presentation\wwwroot\Admin\assets\js\core\bootstrap.bundle.min.js" />
    <Content Include="Presentation\wwwroot\Admin\assets\js\core\bootstrap.min.js" />
    <Content Include="Presentation\wwwroot\Admin\assets\js\core\popper.min.js" />
    <Content Include="Presentation\wwwroot\Admin\assets\js\plugins\bootstrap-notify.js" />
    <Content Include="Presentation\wwwroot\Admin\assets\js\plugins\Chart.extension.js" />
    <Content Include="Presentation\wwwroot\Admin\assets\js\plugins\chartjs.min.js" />
    <Content Include="Presentation\wwwroot\Admin\assets\js\plugins\perfect-scrollbar.min.js" />
    <Content Include="Presentation\wwwroot\Admin\assets\js\plugins\smooth-scrollbar.min.js" />
    <Content Include="Presentation\wwwroot\Admin\assets\js\soft-ui-dashboard.js" />
    <Content Include="Presentation\wwwroot\Admin\assets\js\soft-ui-dashboard.js.map" />
    <Content Include="Presentation\wwwroot\Admin\assets\js\soft-ui-dashboard.min.js" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\bootstrap-grid.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\bootstrap-reboot.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\bootstrap-utilities.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\bootstrap.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\forms\_floating-labels.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\forms\_form-check.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\forms\_form-control.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\forms\_form-range.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\forms\_form-select.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\forms\_form-text.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\forms\_input-group.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\forms\_labels.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\forms\_validation.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\helpers\_clearfix.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\helpers\_color-bg.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\helpers\_colored-links.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\helpers\_position.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\helpers\_ratio.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\helpers\_stacks.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\helpers\_stretched-link.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\helpers\_text-truncation.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\helpers\_visually-hidden.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\helpers\_vr.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_alert.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_backdrop.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_banner.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_border-radius.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_box-shadow.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_breakpoints.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_buttons.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_caret.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_clearfix.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_color-scheme.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_container.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_deprecate.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_forms.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_gradients.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_grid.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_image.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_list-group.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_lists.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_pagination.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_reset-text.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_resize.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_table-variants.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_text-truncate.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_transition.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_utilities.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\mixins\_visually-hidden.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\utilities\_api.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\vendor\_rfs.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_accordion.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_alert.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_badge.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_breadcrumb.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_button-group.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_buttons.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_card.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_carousel.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_close.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_containers.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_dropdown.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_forms.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_functions.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_grid.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_helpers.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_images.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_list-group.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_maps.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_mixins.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_modal.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_nav.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_navbar.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_offcanvas.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_pagination.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_placeholders.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_popover.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_progress.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_reboot.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_root.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_spinners.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_tables.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_toasts.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_tooltip.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_transitions.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_type.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_utilities.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\bootstrap\_variables.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\cards\card-background.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\custom\_styles.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\custom\_variables.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\forms\_form-check.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\forms\_form-select.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\forms\_form-switch.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\forms\_forms.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\forms\_input-group.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\forms\_inputs.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\forms\_labels.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\mixins\mixins.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\mixins\_badge.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\mixins\_colored-shadows.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\mixins\_container.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\mixins\_hover.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\mixins\_social-buttons.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\plugins\free\plugins.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\plugins\free\_flatpickr.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\plugins\free\_nouislider.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\plugins\free\_perfect-scrollbar.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\plugins\free\_prism.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\theme.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_animations.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_avatars.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_badge.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_breadcrumb.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_cards-extend.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_cards.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_choices.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_dark-version.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_dropdowns.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_fixed-plugin.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_form-switch.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_full-calendar.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_header.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_info-areas.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_misc-extend.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_misc.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_navbar-vertical.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_navbar.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_pagination.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_rtl.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_social-buttons.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_table.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_timeline.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_utilities-extend.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_utilities.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\variables\_virtual-reality.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_alert.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_avatars.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_badge.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_breadcrumbs.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_buttons.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_cards.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_dark-version.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_dropdown.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_dropup.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_fixed-plugin.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_footer.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_forms.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_gradients.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_header.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_info-areas.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_misc.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_nav.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_navbar-vertical.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_navbar.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_pagination.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_popovers.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_progress.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_rtl.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_social-buttons.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_tables.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_tilt.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_timeline.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_tooltips.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_typography.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_utilities-extend.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_utilities.scss" />
    <Content Include="Presentation\wwwroot\Admin\assets\scss\soft-ui-dashboard\_variables.scss" />
    <Content Include="Presentation\wwwroot\assets\css\bootstrap.min.css" />
    <Content Include="Presentation\wwwroot\assets\css\icofont.css" />
    <Content Include="Presentation\wwwroot\assets\css\magnific-popup.css" />
    <Content Include="Presentation\wwwroot\assets\css\owl.carousel.css" />
    <Content Include="Presentation\wwwroot\assets\css\responsive.css" />
    <Content Include="Presentation\wwwroot\assets\css\slicknav.min.css" />
    <Content Include="Presentation\wwwroot\assets\css\style.css" />
    <Content Include="Presentation\wwwroot\assets\fonts\icofont7858.eot" />
    <Content Include="Presentation\wwwroot\assets\fonts\icofont7858.svg" />
    <Content Include="Presentation\wwwroot\assets\fonts\icofont7858.ttf" />
    <Content Include="Presentation\wwwroot\assets\fonts\icofont7858.woff" />
    <Content Include="Presentation\wwwroot\assets\img\author.png" />
    <Content Include="Presentation\wwwroot\assets\img\blog-detail.png" />
    <Content Include="Presentation\wwwroot\assets\img\breadcrumb.png" />
    <Content Include="Presentation\wwwroot\assets\img\cast\cast1.png" />
    <Content Include="Presentation\wwwroot\assets\img\cast\cast2.png" />
    <Content Include="Presentation\wwwroot\assets\img\cast\cast3.png" />
    <Content Include="Presentation\wwwroot\assets\img\cast\cast4.png" />
    <Content Include="Presentation\wwwroot\assets\img\cast\cast5.png" />
    <Content Include="Presentation\wwwroot\assets\img\cast\cast6.png" />
    <Content Include="Presentation\wwwroot\assets\img\cast\cast7.png" />
    <Content Include="Presentation\wwwroot\assets\img\favcion.png" />
    <Content Include="Presentation\wwwroot\assets\css\footer-bg.png" />
    <Content Include="Presentation\wwwroot\assets\img\hero-area.png" />
    <Content Include="Presentation\wwwroot\assets\img\loader.gif" />
    <Content Include="Presentation\wwwroot\assets\img\logo.png" />
    <Content Include="Presentation\wwwroot\assets\img\news\news1.jpg" />
    <Content Include="Presentation\wwwroot\assets\img\news\news2.jpg" />
    <Content Include="Presentation\wwwroot\assets\img\news\news3.jpg" />
    <Content Include="Presentation\wwwroot\assets\img\portfolio\portfolio1.png" />
    <Content Include="Presentation\wwwroot\assets\img\portfolio\portfolio2.png" />
    <Content Include="Presentation\wwwroot\assets\img\portfolio\portfolio3.png" />
    <Content Include="Presentation\wwwroot\assets\img\portfolio\portfolio4.png" />
    <Content Include="Presentation\wwwroot\assets\img\portfolio\portfolio5.png" />
    <Content Include="Presentation\wwwroot\assets\img\portfolio\portfolio6.png" />
    <Content Include="Presentation\wwwroot\assets\img\select-icon.png" />
    <Content Include="Presentation\wwwroot\assets\img\sidebar\sidebar1.png" />
    <Content Include="Presentation\wwwroot\assets\img\sidebar\sidebar2.png" />
    <Content Include="Presentation\wwwroot\assets\img\sidebar\sidebar3.png" />
    <Content Include="Presentation\wwwroot\assets\img\sidebar\sidebar4.png" />
    <Content Include="Presentation\wwwroot\assets\img\slide1.png" />
    <Content Include="Presentation\wwwroot\assets\img\slide2.png" />
    <Content Include="Presentation\wwwroot\assets\img\slide3.png" />
    <Content Include="Presentation\wwwroot\assets\img\slide4.jpg" />
    <Content Include="Presentation\wwwroot\assets\img\video\video1.png" />
    <Content Include="Presentation\wwwroot\assets\img\video\video2.png" />
    <Content Include="Presentation\wwwroot\assets\img\video\video3.png" />
    <Content Include="Presentation\wwwroot\assets\img\video\video4.png" />
    <Content Include="Presentation\wwwroot\assets\img\video\video5.png" />
    <Content Include="Presentation\wwwroot\assets\js\bootstrap.min.js" />
    <Content Include="Presentation\wwwroot\assets\js\isotope.pkgd.min.js" />
    <Content Include="Presentation\wwwroot\assets\js\jquery.magnific-popup.min.js" />
    <Content Include="Presentation\wwwroot\assets\js\jquery.min.js" />
    <Content Include="Presentation\wwwroot\assets\js\jquery.slicknav.min.js" />
    <Content Include="Presentation\wwwroot\assets\js\main.js" />
    <Content Include="Presentation\wwwroot\assets\js\owl.carousel.min.js" />
    <Content Include="Presentation\wwwroot\content\images\cast\image\32f8ae9e26e34cc68979e129899fa239.png" />
    <Content Include="Presentation\wwwroot\content\images\cast\image\44d3a570843648cf8d0a7f907bd92b14.jpg" />
    <Content Include="Presentation\wwwroot\content\images\cast\image\5c859dea0ea04cb28e0eb28a5fe45e07.jpg" />
    <Content Include="Presentation\wwwroot\content\images\cast\image\606cbae95dc14ee3b281bdd8f444234a.jpg" />
    <Content Include="Presentation\wwwroot\content\images\cast\image\8efaf971b739418e94dc9b33343fdefe.png" />
    <Content Include="Presentation\wwwroot\content\images\cast\image\e173d91d386645d496110f1ec38b4016.jpg" />
    <Content Include="Presentation\wwwroot\content\images\cast\image\e21da4a9d85c426d8020330a8303d0b4.jpg" />
    <Content Include="Presentation\wwwroot\content\images\cast\thumb\32f8ae9e26e34cc68979e129899fa239.png" />
    <Content Include="Presentation\wwwroot\content\images\cast\thumb\44d3a570843648cf8d0a7f907bd92b14.jpg" />
    <Content Include="Presentation\wwwroot\content\images\cast\thumb\5c859dea0ea04cb28e0eb28a5fe45e07.jpg" />
    <Content Include="Presentation\wwwroot\content\images\cast\thumb\606cbae95dc14ee3b281bdd8f444234a.jpg" />
    <Content Include="Presentation\wwwroot\content\images\cast\thumb\8efaf971b739418e94dc9b33343fdefe.png" />
    <Content Include="Presentation\wwwroot\content\images\cast\thumb\e173d91d386645d496110f1ec38b4016.jpg" />
    <Content Include="Presentation\wwwroot\content\images\cast\thumb\e21da4a9d85c426d8020330a8303d0b4.jpg" />
    <Content Include="Presentation\wwwroot\content\images\movie\image\0ecb58d16d9a43e7bac48c3d94d31c23.jpg" />
    <Content Include="Presentation\wwwroot\content\images\movie\image\7c2839abd2544093b339f2797168953c.jpg" />
    <Content Include="Presentation\wwwroot\content\images\movie\image\96452a5a9a314eda87af1d7c0ad424b4.jpg" />
    <Content Include="Presentation\wwwroot\content\images\movie\image\c718d259eb0d44fbb5bd28e6d33f2b07.jfif" />
    <Content Include="Presentation\wwwroot\content\images\movie\image\fa30fc3b684c4701ae83cb8abc8a34f1.jfif" />
    <Content Include="Presentation\wwwroot\content\images\movie\image\fdb93f7619c445238303a964b374309b.jpg" />
    <Content Include="Presentation\wwwroot\content\images\movie\thumb\0ecb58d16d9a43e7bac48c3d94d31c23.jpg" />
    <Content Include="Presentation\wwwroot\content\images\movie\thumb\7c2839abd2544093b339f2797168953c.jpg" />
    <Content Include="Presentation\wwwroot\content\images\movie\thumb\96452a5a9a314eda87af1d7c0ad424b4.jpg" />
    <Content Include="Presentation\wwwroot\content\images\movie\thumb\c718d259eb0d44fbb5bd28e6d33f2b07.jfif" />
    <Content Include="Presentation\wwwroot\content\images\movie\thumb\fa30fc3b684c4701ae83cb8abc8a34f1.jfif" />
    <Content Include="Presentation\wwwroot\content\images\movie\thumb\fdb93f7619c445238303a964b374309b.jpg" />
    <Content Include="Presentation\wwwroot\content\images\movie\video\08ead564d41249bfb43bfeef68449886.mp4" />
    <Content Include="Presentation\wwwroot\content\images\movie\video\137bf47935d4441eb5d8b142ef72bb8e.mp4" />
    <Content Include="Presentation\wwwroot\content\images\movie\video\7f8647850de74db89539609fe821dc72.mp4" />
    <Content Include="Presentation\wwwroot\content\images\movie\video\7fc7e8921a0a4f7c83fb7ad8c4cd69ae.mp4" />
    <Content Include="Presentation\wwwroot\content\images\movie\video\ae9ebe93c9b7430490d5de25de0543da.mp4" />
    <Content Include="Presentation\wwwroot\content\images\movie\video\fddbe9506367418b8b9c67f5bbe5463c.mp4" />
    <Content Include="Presentation\wwwroot\content\images\news\image\8ee1115aa4e24475a0a64efac52dedde.jpg" />
    <Content Include="Presentation\wwwroot\content\images\news\image\e0de1934f0714120b5fefb4313e896e5.jpg" />
    <Content Include="Presentation\wwwroot\content\images\news\thumb\8ee1115aa4e24475a0a64efac52dedde.jpg" />
    <Content Include="Presentation\wwwroot\content\images\news\thumb\e0de1934f0714120b5fefb4313e896e5.jpg" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-grid.css" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-grid.css.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-grid.min.css" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-grid.min.css.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.css" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.css.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.min.css" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.min.css.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.css" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.css.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.min.css" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.min.css.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.css" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.css.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.min.css" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.min.css.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.css" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.css.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.min.css" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.min.css.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.css" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.css.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.min.css" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.min.css.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap.css" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap.css.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap.min.css" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap.min.css.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.css" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.css.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.min.css" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.min.css.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.js" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.js.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.min.js" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.min.js.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\js\bootstrap.esm.js" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\js\bootstrap.esm.js.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\js\bootstrap.esm.min.js" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\js\bootstrap.esm.min.js.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\js\bootstrap.js" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\js\bootstrap.js.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\js\bootstrap.min.js" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\dist\js\bootstrap.min.js.map" />
    <Content Include="Presentation\wwwroot\lib\bootstrap\LICENSE" />
    <Content Include="Presentation\wwwroot\lib\jquery-validation-unobtrusive\jquery.validate.unobtrusive.js" />
    <Content Include="Presentation\wwwroot\lib\jquery-validation-unobtrusive\jquery.validate.unobtrusive.min.js" />
    <Content Include="Presentation\wwwroot\lib\jquery-validation-unobtrusive\LICENSE.txt" />
    <Content Include="Presentation\wwwroot\lib\jquery-validation\dist\additional-methods.js" />
    <Content Include="Presentation\wwwroot\lib\jquery-validation\dist\additional-methods.min.js" />
    <Content Include="Presentation\wwwroot\lib\jquery-validation\dist\jquery.validate.js" />
    <Content Include="Presentation\wwwroot\lib\jquery-validation\dist\jquery.validate.min.js" />
    <Content Include="Presentation\wwwroot\lib\jquery-validation\LICENSE.md" />
    <Content Include="Presentation\wwwroot\lib\jquery\dist\jquery.js" />
    <Content Include="Presentation\wwwroot\lib\jquery\dist\jquery.min.js" />
    <Content Include="Presentation\wwwroot\lib\jquery\dist\jquery.min.map" />
    <Content Include="Presentation\wwwroot\lib\jquery\LICENSE.txt" />
    <Content Include="Presentation\wwwroot\lib\madules\Madules.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.2" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.4" />
  </ItemGroup>

</Project>
